Use latest `create-jest-runner` dependency
jest-community/jest-runner-eslint pull request #106
Opened 2021-04-06 19:52 UTC by mrtnzlml

2021-04-06 23:43 UTC, ljharb approved these changes

2021-04-06 23:44 UTC, ljharb requested changes
Actually, it looks like tests are failing in node 8, because of syntax node 8 doesn't support, so it doesn't seem like we can update to this version without a breaking change.

2021-04-06 23:44 UTC, ljharb commented on CONTRIBUTING.md
> +   cd jest-runner-eslint
this is a good change regardless

2021-04-07 00:11 UTC, mrtnzlml commented
> Actually, it looks like tests are failing in node 8, because of syntax node 8 doesn't support, so it doesn't seem like we can update to this version without a breaking change.

@ljharb Is there anything preventing us to do so? I see that this project didn't reach a stable version yet (it's 0.10.0) so I could just send another PR. But not sure if there is any motivation to keep the node 8 support though. 🤔

2021-04-07 01:24 UTC, ljharb commented
Dropping support is something that should require motivation; retaining it should be the default. What's the concrete benefit of updating here, and/or dropping support, that would justify excluding those users?

2021-04-07 06:51 UTC, SimenB commented on package.json
>      "cosmiconfig": "^6.0.0",
if/when we upgrade, these should be bumped as well

2021-04-07 14:29 UTC, mrtnzlml commented
The motivation for this PR was to use the latest dependencies in our project and Node 8 didn't seem like a huge concern considering it's well beyond its end of life and the latest Jest and Eslint don't support such an old version either.

I do not have any other arguments for this PR - just the desire to be up to date.

2021-04-07 14:29 UTC, closed without merging