Add peer dep support for jest 27
jest-community/jest-runner-eslint pull request #114
Opened 2021-06-08 19:14 UTC by Whoaa512

2021-06-08 19:20 UTC, ljharb requested changes
Looks great - let’s also add it to the [test matrix](https://github.com/jest-community/jest-runner-eslint/blob/main/.travis.yml)

2021-06-08 20:27 UTC, ljharb approved these changes

2021-06-15 08:26 UTC, SimenB approved these changes

2021-06-15 08:26 UTC, merged

2021-06-15 08:34 UTC, SimenB commented
Released in 0.10.1